# Generated by Django 5.0 on 2024-04-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolManagementSystam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('opening', models.DateTimeField(null=True)),
                ('Principal', models.IntegerField(null=True)),
                ('teaches', models.IntegerField(null=True)),
                ('students', models.IntegerField(null=True)),
                ('building', models.IntegerField(null=True)),
                ('campus', models.IntegerField(null=True)),
                ('bus', models.IntegerField(null=True)),
                ('about', models.TextField(null=True)),
                ('time', models.TimeField(null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('experience', models.FloatField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('class_name', models.IntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('fees', models.IntegerField(null=True)),
                ('standard', models.IntegerField(null=True)),
            ],
        ),
    ]
