# Generated by Django 5.0 on 2024-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_int', models.BigIntegerField(serialize=False, verbose_name='ID')),
                ('binary_field', models.BinaryField(null=True)),
                ('boolean_field', models.BooleanField(blank=True, null=True)),
                ('char', models.CharField(max_length=255, null=True)),
                ('date_fields', models.DateField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('float', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('integer', models.IntegerField(null=True)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('positive_integer', models.PositiveIntegerField(null=True)),
                ('positive_small_integer', models.PositiveSmallIntegerField(null=True)),
                ('slug_fields', models.SlugField(max_length=200, null=True)),
                ('small_integer', models.SmallIntegerField(null=True)),
                ('Text_fields', models.TextField(null=True)),
                ('time_field', models.TimeField(null=True)),
                ('url', models.URLField(null=True)),
                ('uuid', models.UUIDField(null=True)),
            ],
        ),
    ]
